"""
CAR CONFIG

This file is read by your car application's manage.py script to change the car
performance.

EXAMPLE
-----------
import dk
cfg = dk.load_config(config_path='~/d2/config.py')
print(cfg.CAMERA_RESOLUTION)

"""

import os

# PATHS
CAR_PATH = PACKAGE_PATH = os.path.dirname(os.path.realpath(__file__))
DATA_PATH = os.path.join(CAR_PATH, 'data')
MODELS_PATH = os.path.join(CAR_PATH, 'models')

# VEHICLE
DRIVE_LOOP_HZ = 40
MAX_LOOPS = 100000

# CAMERA
CAMERA_RESOLUTION = (128, 160)  # (height, width)
CAMERA_FRAMERATE = DRIVE_LOOP_HZ

# STEERING
STEERING_CHANNEL = 0
TX_STEERING_MIN = 1060
TX_STEERING_MAX = 1960
STEERING_LEFT_PWM = ((TX_STEERING_MAX) / (16666 / 4095))
STEERING_RIGHT_PWM = ((TX_STEERING_MIN) / (16666 / 4095))

############
# THROTTLE #
############
THROTTLE_CHANNEL = 1
THROTTLE_FORWARD_PWM = 400
THROTTLE_STOPPED_PWM = 360
THROTTLE_REVERSE_PWM = 310

THROTTLE_STEERING_ENABLE = True
# Max speed between 0-1
THROTTLE_MIN_SPEED = 0.5
THROTTLE_MAX_SPEED = 1.0
THROTTLE_SAFE_ANGLE = 0.3
THROTTLE_DANGEROUS_ANGLE = 0.8

# TRAINING
BATCH_SIZE = 128
TRAIN_TEST_SPLIT = 0.8

# JOYSTICK
USE_JOYSTICK_AS_DEFAULT = False
JOYSTICK_MAX_THROTTLE = 0.25
JOYSTICK_STEERING_SCALE = 1.0
AUTO_RECORD_ON_THROTTLE = True

# Contours detection
POLY_DP_MIN = 4
ARC_LENGTH_MIN = 15
ARC_LENGTH_MAX = 100000000

#############
#  Threshold #
#############
#  Static implementation
THRESHOLD_LIMIT_MIN = 180
THRESHOLD_LIMIT_MAX = 230

#  Dynamic
THRESHOLD_DYNAMIC_ENABLE = True
THRESHOLD_DYNAMIC_INIT = 180
THRESHOLD_DYNAMIC_DELTA = 10

# PILOT
DEBUG_PILOT = True
USE_ONLY_NEAR_CONTOUR = True

OUT_ZONE_PERCENT = 20
CENTRAL_ZONE_PERCENT = 20
